conil_platform_apis.settings:
  type: config_object
  label: 'Sensors configuration'
  mapping:
    base_url:
      type: string
      label: 'Base url'
    key_1:
      type: string
      label: 'Key 1'
    value_1:
      type: string
      label: 'Value 1'
    key_2:
      type: string
      label: 'Key 2'
    value_2_conteo:
      type: string
      label: 'Value 2 conteo'
    value_2_meteo:
      type: string
      label: 'Value 2 meteo'
    value_2_airquality:
      type: string
      label: 'Value 2 air quality'




