conil_totem_sync.settings:
  type: config_object
  label: 'Conil Totem conection settings.'
  mapping:
    active:
      type: boolean
      label: 'Check if the service is activated.'
    environment:
      type: text
      label: 'The selected environment.'
    last_update:
      type: text
      label: 'Last syncronization with totem.'
