conil_totem_sync.conil_ws_entity.*:
  type: config_entity
  label: 'Conil WS entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
