<?php

/**
 * @file
 * This is the module for conil_weather.
 */

/**
 * Implements hook_cron().
 */
function conil_weather_cron() {
  // Creamos la instancia del servicio de conexion con NFS.
  $servicio = \Drupal::service('conil_weather.weather');
  $servicio->printPdfWeather();
}

/**
 * Implements hook_theme().
 */
function conil_weather_theme() {
  $theme = [];
  $theme['template_totem_pdf_weather'] = [
    'variables' => [
      'css' => NULL,
      'background' => null,
      'qr' => NULL,
      'conil_logo' => NULL,
      'wind_img' => NULL,
      'drop_img' => NULL,
      'data' => NULL,
    ],
  ];
  return $theme;
}
