apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnt-pvc
  namespace: portales
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc