content_grids.settings:
  type: config_object
  label: 'Content Grids Settings'
  mapping:
    api_key:
      type: string
      label: 'API key del totem'
    url_api:
      type: string
      label: 'Url de acceso a la API'

